/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package excelproj1;

import java.io.File;
import java.util.Date;
import javax.swing.JFileChooser;

/**
 *
 * @author WoodmDav
 */
public class jFrame extends javax.swing.JFrame {
    
    String lastWeek = myTools.getLastWeek();
    boolean useDefaultGO = true;
    File weeklyFT;
    File connReport;
    File ytdRegCSV;
    File weeklyReg;
    File updatedRegReport;
            
            
            
    /**
     * Creates new form jFrame
     */
    public jFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRegButton = new javax.swing.JButton();
        jConnButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jGoButton = new javax.swing.JButton();
        jOutputLabel = new javax.swing.JLabel();
        jNewGen2Label = new javax.swing.JLabel();
        jNiuxFWLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jRegButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jRegButton.setText("REGISTRATION");
        jRegButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRegButtonActionPerformed(evt);
            }
        });

        jConnButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jConnButton.setText("FIELD TRIAL");
        jConnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jConnButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("LOAD FILES");

        jGoButton.setText("GO");
        jGoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGoButtonActionPerformed(evt);
            }
        });

        jOutputLabel.setText("Output:");
        jOutputLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jNewGen2Label.setText("New GEN2 FW");

        jNiuxFWLabel.setText("New NIUX FW");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jOutputLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(263, 263, 263)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jNewGen2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jNiuxFWLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jConnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jRegButton)
                                .addGap(37, 37, 37)))
                        .addComponent(jGoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRegButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jConnButton, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jGoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jNiuxFWLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jNewGen2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(69, 69, 69)))
                .addComponent(jOutputLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jConnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jConnButtonActionPerformed

        JFileChooser filePick = new JFileChooser("src//");
        
        //WeeklyReport
        filePick.setDialogTitle("Weekly Report");
        int returnValue = filePick.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            weeklyFT = filePick.getSelectedFile();
            System.out.println(weeklyFT.getAbsolutePath());

            //ConnReport
            filePick.setDialogTitle("Connectivity Report");
            returnValue = filePick.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                    connReport = filePick.getSelectedFile();
                    System.out.println(connReport.getAbsolutePath());
                    
                    useDefaultGO = false;//if user successfully chooses two files, they cannot use default GO button
            }
        }
    }//GEN-LAST:event_jConnButtonActionPerformed

    private void jGoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGoButtonActionPerformed

        String path = "src//";
        if(useDefaultGO == true){
            System.out.println("Logic for useDefaults true");
            connReport = new File(path + "Connectivity Report " + lastWeek + ".xlsx");
            updatedRegReport = new File(path + "YTD Updated Registration Report " + lastWeek + ".xlsx");
            weeklyFT = new File(path + "Weekly_Report.csv");
            weeklyReg = new File(path + "Weekly_Reg_Report.csv");
            ytdRegCSV = new File(path + "YTD_Reg_Report.csv");
        } else {
            System.out.println("Logic for useDefaults false");
        }
        ConnectivityReport.executeAutomation(weeklyFT, connReport);
        jOutputLabel.setText(jOutputLabel.getText() + "\n\tConnectivity Report Success");
        RegistrationReport.executeAutomation(weeklyReg, ytdRegCSV, updatedRegReport);
        jOutputLabel.setText(jOutputLabel.getText() + "\n\tRegistration Report Success");
    }//GEN-LAST:event_jGoButtonActionPerformed

    private void jRegButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRegButtonActionPerformed

        JFileChooser filePick = new JFileChooser("src//");
        
        //YRD REG
        filePick.setDialogTitle("YTD Reg Report");
        int returnValue = filePick.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            ytdRegCSV = filePick.getSelectedFile();
            System.out.println(ytdRegCSV.getAbsolutePath());

            //WeeklyReg
            filePick.setDialogTitle("Weekly Reg Report");
            returnValue = filePick.showOpenDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                weeklyReg = filePick.getSelectedFile();
                System.out.println(weeklyReg.getAbsolutePath());

                //YTD Updated Registration Report
                filePick.setDialogTitle("YTD Updated Registration Report");
                returnValue = filePick.showOpenDialog(null);
                if (returnValue == JFileChooser.APPROVE_OPTION) {
                        updatedRegReport = filePick.getSelectedFile();
                        System.out.println(updatedRegReport.getAbsolutePath());

                        useDefaultGO = false;//if user successfully chooses three files, they cannot use default GO button
                }
            }
        }
    }//GEN-LAST:event_jRegButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jConnButton;
    private javax.swing.JButton jGoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jNewGen2Label;
    private javax.swing.JLabel jNiuxFWLabel;
    private javax.swing.JLabel jOutputLabel;
    private javax.swing.JButton jRegButton;
    // End of variables declaration//GEN-END:variables
}
